name: NativeSpeechTranslator
options:
  bundleIdPrefix: com.example
  developmentLanguage: ja
  fileTypes:
    icon:
      file: true # IconComposer
packages:
  SwiftDependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: 1.0.0
targets:
  NativeSpeechTranslator:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources: 
      - NativeSpeechTranslator
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.NativeSpeechTranslator
        INFOPLIST_KEY_CFBundleDisplayName: "Native Speech Translator"
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "音声を文字に変換するために使用します。"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "システム音声をキャプチャするためにマイク入力を使用します。"
        INFOPLIST_KEY_CFBundleIconFile: AppIcon
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: SwiftDependencies
        product: Dependencies
      - package: SwiftDependencies
        product: DependenciesMacros
    entitlements:
        path: NativeSpeechTranslator/NativeSpeechTranslator.entitlements
  NativeSpeechTranslatorTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - NativeSpeechTranslatorTests
    dependencies:
      - target: NativeSpeechTranslator
      - package: SwiftDependencies
        product: Dependencies
      - package: SwiftDependencies
        product: DependenciesMacros
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.example.NativeSpeechTranslatorTests
schemes:
  NativeSpeechTranslator:
    build:
      targets:
        NativeSpeechTranslator: all
        NativeSpeechTranslatorTests: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - NativeSpeechTranslatorTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  Release:
    build:
      targets:
        NativeSpeechTranslator: all
    run:
      config: Release
    test:
      config: Release
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release

